/**
    Copyright 2014-2015 Amazon.com, Inc. or its affiliates. All Rights Reserved.

    Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with the License. A copy of the License is located at

        http://aws.amazon.com/apache2.0/

    or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
*/

module.exports = {
"our father": "<speak><p>Our Father, Who art in heaven</p> <p>Hallowed be Thy Name</p> <p>Thy kingdom come,</p> <p>Thy will be done,</p> <p>on earth as it is in heaven.</p> <p>Give us this day our daily bread,</p> <p>and forgive us our trespasses, as we forgive those who trespass against us;</p> <p>and lead us not into temptation,</p> <p>but deliver us from evil.</p> <p>Amen.</p></speak>",
"hail mary": "<speak><p>Hail Mary full of Grace,</p> <p>the Lord is with thee.</p> <p>Blessed are thou among women and blessed is the fruit of thy womb Jesus.</p> <p>Holy Mary Mother of God,</p> <p>pray for us sinners now and at the hour of our death</p> <p>Amen.</p></speak>",    
"glory be": "<speak><p>Glory be to the Father,</p> <p>and to the Son,</p> <p>and to the Holy Spirit,</p> <p>as it was in the beginning,</p> <p>it is now,</p> <p>and ever shall be,</p> <p>world without end.</p> <p>Amen.</p></speak>",
"the apostle's creed": "<speak><p>I believe in God,</p><p>the Father Almighty,</p><p> Creator of Heaven and earth;</p><p> and in Jesus Christ,</p><p> His only Son,</p><p>Our Lord,</p><p> Who was conceived by the Holy Spirit,</p><p> born of the Virgin Mary,</p><p> suffered under Pontius Pilate,</p><p> was crucified,</p><p> died,</p><p> and was buried.</p><p> He descended into Hell.</p><p> The third day He arose again from the dead;</p><p> He ascended into Heaven, </p><p> and is sitteth at the right hand of God, the Father Almighty;</p><p> from there He shall come to judge the living and the dead.</p><p> I believe in the Holy Spirit,</p><p> the holy Catholic Church,</p><p>the communion of saints,</p><p> the forgiveness of sins,</p><p>the resurrection of the body,</p><p> and the life everlasting.</p><p> Amen.</p></speak>",
"the creed": "<speak><p>I believe in God,</p><p>the Father Almighty,</p><p> Creator of Heaven and earth;</p><p> and in Jesus Christ,</p><p> His only Son,</p><p>Our Lord,</p><p> Who was conceived by the Holy Spirit,</p><p> born of the Virgin Mary,</p><p> suffered under Pontius Pilate,</p><p> was crucified,</p><p> died,</p><p> and was buried.</p><p> He descended into Hell.</p><p> The third day He arose again from the dead;</p><p> He ascended into Heaven, </p><p> and is sitteth at the right hand of God, the Father Almighty;</p><p> from there He shall come to judge the living and the dead.</p><p> I believe in the Holy Spirit,</p><p> the holy Catholic Church,</p><p>the communion of saints,</p><p> the forgiveness of sins,</p><p>the resurrection of the body,</p><p> and the life everlasting.</p><p> Amen.</p></speak>",
"the long creed": "<speak><p>I believe in one God,</p><p> the Father almighty,</p><p> maker of heaven and earth,</p><p> of all things visible and invisible;</p><p> I believe in one Lord Jesus Christ</p><p> the only begotten Son of God, </p><p>born of the Father before all ages.</p><p> God from God,</p><p>  light from light,</p><p> true God from true God,</p><p> begotten, not made,</p><p> consubstantial with the Father,</p><p> through him all things were made</p><p> For us men and for our salvation he came down from heaven,</p><p> and by the Holy Spirit was incarnate of the Virgin Mary, and became man.</p><p> For our sake he was crucified under Pontius Pilate, </p><p> he suffered death and was buried,</p><p> and rose again on the third day according to the Scriptures </p><p> He ascended into heaven and is seated at the right hand of the Father. </p><p>He will come again in glory to judge the living and the dead </p><p> and his kingdom will have no end.</p><p> I believe in the Holy Spirit, </p><p>the Lord </p><p> the giver of life, </p><p>Who proceeds from the Father, </p><p>who with the Father and the Son is adored and glorified,</p><p>Who spoke through the prophets;</p><p>I believe in one holy,</p><p>Catholic,</p><p> and apostolic Church.</p><p> I confess one baptism for the forgiveness of sins;</p><p> I look forward to the resurrection of the dead and the life of the world to come. </p><p>Amen.</p></speak>",
"the nicene creed": "<speak><p>I believe in one God,</p><p> the Father almighty,</p><p> maker of heaven and earth,</p><p> of all things visible and invisible;</p><p> I believe in one Lord Jesus Christ</p><p> the only begotten Son of God, </p><p>born of the Father before all ages.</p><p> God from God,</p><p>  light from light,</p><p> true God from true God,</p><p> begotten, not made,</p><p> consubstantial with the Father,</p><p> through him all things were made</p><p> For us men and for our salvation he came down from heaven,</p><p> and by the Holy Spirit was incarnate of the Virgin Mary, and became man.</p><p> For our sake he was crucified under Pontius Pilate, </p><p> he suffered death and was buried,</p><p> and rose again on the third day according to the Scriptures </p><p> He ascended into heaven and is seated at the right hand of the Father. </p><p>He will come again in glory to judge the living and the dead </p><p> and his kingdom will have no end.</p><p> I believe in the Holy Spirit, </p><p>the Lord </p><p> the giver of life, </p><p>Who proceeds from the Father, </p><p>who with the Father and the Son is adored and glorified,</p><p>Who spoke through the prophets;</p><p>I believe in one holy,</p><p>Catholic,</p><p> and apostolic Church.</p><p> I confess one baptism for the forgiveness of sins;</p><p> I look forward to the resurrection of the dead and the life of the world to come. </p><p>Amen.</p></speak>",
"the nicene creed of the eastern orthodox": "<speak><p>I believe in one God,</p><p> the Father almighty,</p><p> maker of heaven and earth,</p><p> of all things visible and invisible;</p><p> I believe in one Lord Jesus Christ</p><p> the only begotten Son of God, </p><p>born of the Father before all ages.</p><p> God from God,</p><p>  light from light,</p><p> true God from true God,</p><p> begotten, not made,</p><p> consubstantial with the Father,</p><p> through him all things were made</p><p> For us men and for our salvation he came down from heaven,</p><p> and by the Holy Spirit was incarnate of the Virgin Mary, and became man.</p><p> For our sake he was crucified under Pontius Pilate, </p><p> he suffered death and was buried,</p><p> and rose again on the third day according to the Scriptures </p><p> He ascended into heaven and is seated at the right hand of the Father. </p><p>He will come again in glory to judge the living and the dead </p><p> and his kingdom will have no end.</p><p> I believe in the Holy Spirit, </p><p>the Lord </p><p> the giver of life, </p><p>Who proceeds from the Father, </p><p>who with the Father and the Son is adored and glorified,</p><p>Who spoke through the prophets;</p><p>I believe in one holy,</p><p>Catholic,</p><p> and apostolic Church.</p><p> I confess one baptism for the forgiveness of sins;</p><p> I look forward to the resurrection of the dead and the life of the world to come. </p><p>Amen.</p></speak>",
"hail holy queen": "<speak><p>Hail Holy Queen, Mother of mercy,</p><p> our life, our sweetness and our hope.</p><p> To thee do we cry, poor banished children of Eve: </p><p>to thee do we send up our sighs. mourning and weeping in this valley of tears.</p><p> Turn then, most gracious Advocate, thine eyes of mercy toward us,</p><p> and after this, our exile </p><p>show unto us the blessed fruit of thy womb Jesus. </p><p>O clement, </p><p>O loving, </p><p>O sweet Virgin Mary! </p><p> Pray for us, O holy Mother of God. </p><p>That we may be made worthy of the promises of Christ.</p><p>Amen.</p></speak>",
"anima christi": "<speak>Soul of Christ, make me holy. Body of Christ, be my salvation. Blood of Christ, let me drink your wine. Water flowing from the side of Christ, wash me. clean Passion of Christ, strengthen me. Kind Jesus, hear my prayer. Hide me within your wounds And keep me close to you. Defend me from the evil enemy. And call me at the hour of my death, To the fellowship of your saints. That I might sing your praise with them for all eternity. Amen.</speak>",
"anima kristy": "<speak>Soul of Christ, make me holy. Body of Christ, be my salvation. Blood of Christ, let me drink your wine. Water flowing from the side of Christ, wash me. clean Passion of Christ, strengthen me. Kind Jesus, hear my prayer. Hide me within your wounds And keep me close to you. Defend me from the evil enemy. And call me at the hour of my death, To the fellowship of your saints. That I might sing your praise with them for all eternity. Amen.</speak>",
"memorare": "<speak>Remember, O most gracious Virgin Mary, that never was it known, that any one who fled to thy protection. implored thy help, or sought thy intercession, was left unaided. Inspired by this confidence, We fly unto thee, O Virgin of virgins, my Mother<p> to thee do we come</p> before thee we stand, sinful, and sorrowful. O Mother of the Word Incarnate, despise not our petitions. but in thy mercy, hear and answer them. Amen.</speak>",
"angelus": "<speak>The Angel of the Lord declared unto Mary." + "<break time=\"1s\"/>" + "And she conceived by the Holy Spirit. Hail Mary full of Grace, the Lord is with thee. Blessed are thou among women and blessed is the fruit of thy womb Jesus. Holy Mary Mother of God, pray for us sinners now and at the hour of our death Amen." + "<break time=\"1s\"/>" + "Behold the handmaid of the Lord." + "<break time=\"1s\"/>" + "Be it done unto me according to thy word." + "<break time=\"1s\"/>" + "Hail Mary full of Grace, the Lord is with thee. Blessed are thou among women and blessed is the fruit of thy womb Jesus. Holy Mary Mother of God, pray for us sinners now and at the hour of our death Amen."+ "<break time=\"1s\"/>" + "And the Word was made Flesh." + "<break time=\"1s\"/>" + "And dwelt among us. Hail Mary full of Grace, the Lord is with thee. Blessed are thou among women and blessed is the fruit of thy womb Jesus. Holy Mary Mother of God, pray for us sinners now and at the hour of our death Amen." + "<break time=\"1s\"/>" + " Pray for us, O Holy Mother of God." + "<break time=\"1s\"/>" + "That we may be made worthy of the promises of Christ." + "<break time=\"1s\"/>" + " Let us pray:  Pour forth, we beseech Thee, O Lord, Thy grace into our hearts; that, we to whom the Incarnation of Christ, Thy Son, was made known by the message of an Angel, may by His Passion and Cross, be brought to the glory of His Resurrection through the same Christ our Lord. Amen.</speak>",
"the angelus": "<speak>The Angel of the Lord declared unto Mary." + "<break time=\"1s\"/>" + "And she conceived by the Holy Spirit. Hail Mary full of Grace, the Lord is with thee. Blessed are thou among women and blessed is the fruit of thy womb Jesus. Holy Mary Mother of God, pray for us sinners now and at the hour of our death Amen." + "<break time=\"1s\"/>" + "Behold the handmaid of the Lord." + "<break time=\"1s\"/>" + "Be it done unto me according to thy word." + "<break time=\"1s\"/>" + "Hail Mary full of Grace, the Lord is with thee. Blessed are thou among women and blessed is the fruit of thy womb Jesus. Holy Mary Mother of God, pray for us sinners now and at the hour of our death Amen."+ "<break time=\"1s\"/>" + "And the Word was made Flesh." + "<break time=\"1s\"/>" + "And dwelt among us. Hail Mary full of Grace, the Lord is with thee. Blessed are thou among women and blessed is the fruit of thy womb Jesus. Holy Mary Mother of God, pray for us sinners now and at the hour of our death Amen." + "<break time=\"1s\"/>" + " Pray for us, O Holy Mother of God." + "<break time=\"1s\"/>" + "That we may be made worthy of the promises of Christ." + "<break time=\"1s\"/>" + " Let us pray:  Pour forth, we beseech Thee, O Lord, Thy grace into our hearts; that, we to whom the Incarnation of Christ, Thy Son, was made known by the message of an Angel, may by His Passion and Cross, be brought to the glory of His Resurrection through the same Christ our Lord. Amen.</speak>",
"saint michael prayer": "<speak>Saint Michael, the Archangel, defend us in battle. Be our protection against the wickedness and snares of the devil. May God rebuke him, we humbly pray; and do thou, O Prince of the heavenly host, by the power of God cast into hell Satan and all the evil spirits who prowl throughout the world seeking the ruin of souls. Amen.</speak>",
"saint michael": "<speak>Saint Michael, the Archangel, defend us in battle. Be our protection against the wickedness and snares of the devil. May God rebuke him, we humbly pray; and do thou, O Prince of the heavenly host, by the power of God cast into hell Satan and all the evil spirits who prowl throughout the world seeking the ruin of souls. Amen.</speak>",
"act of contrition": "<speak>O my God, I am heartfully sorry for having offended You, and I detest all my sins because of Your just punishment, but most of all because I have offended you, my God. Who are all good, and deserving of all my love. I firmly resolve, with the help of Your grace, to sin no more, and to avoid the near occasion of sin. Amen.</speak>",
"miraculous medal": "<speak>O Mary, conceived without sin, pray for us who have recourse to thee, and for those who do not have recourse to thee, especially the enemies of the Church and those recommended to thee. Amen.</speak>",
"morning offering": "<speak>Dear Lord, I do not know what will happen to me today. I only know that nothing will happen that was not foreseen by You, and directed to my greater good from all eternity. I adore Your holy and unfathomable plans, and submit to them with all my heart for love of You, the Pope, and the Immaculate Heart of Mary. Amen.</speak>",
"guardian angel": "<speak>Angel of God, my Guardian dear, to whom God's love commits me here, ever this day (or night) be at my side, to light and guard, to rule and guide. Amen.</speak>",
"grace before meals": "<speak>Bless us, O Lord, and these Thy gifts, which we are about to receive from Thy bounty, through Christ our Lord. Amen.</speak>",
"grace after meals": "<speak>We give you thanks for all your benefits, Almighty God, who lives and reignes world without end. Amen. May the souls of the faithful departed, through the mercy of God, rest in peace. Amen.</speak>",
"prayer before meals":"<speak>Bless us, O Lord, and these Thy gifts, which we are about to receive from Thy bounty, through Christ our Lord. Amen.</speak>",
"prayer after meals": "<speak>We give you thanks for all your benefits, Almighty God, who lives and reignes world without end. Amen. May the souls of the faithful departed, through the mercy of God, rest in peace. Amen.</speak>",
"serenity prayer": "<speak>O God, grant me the serenity to accept the things I cannot change. the courage to change the things I can. and the wisdom to know the difference. Living one day at a time, enjoying one moment at a time. Accepting hardships as the pathway to peace. Taking, as he did, the sinful world as it is, not as I would want it. Trusting that you will make all things right if I surrender to your will; that I may be reasonably happy in this life, and supremely happy with you forever. Amen.</speak>",
"saint jose maria prayer": "<speak> O God, through the mediation of Mary our Mother, you granted your priest St. Jose Maria countless graces, choosing him as a most faithful instrument to found Opus Dei, a way of sanctification in daily work and in the fulfillment of the Christian's ordinary duties. Grant that I too may learn to turn all the circumstances and events of my life into occasions of loving You and serving the Church, the Pope and all souls with joy and simplicity, lighting up the pathways of this earth with faith and love. Deign to grant me, through the intercession of Saint Jose Maria, the favor of" + "<break time=\"3s\"/>" + "Amen </speak>",
"jose maria prayer": "<speak> O God, through the mediation of Mary our Mother, you granted your priest St. Jose Maria countless graces, choosing him as a most faithful instrument to found Opus Dei, a way of sanctification in daily work and in the fulfillment of the Christian's ordinary duties. Grant that I too may learn to turn all the circumstances and events of my life into occasions of loving You and serving the Church, the Pope and all souls with joy and simplicity, lighting up the pathways of this earth with faith and love. Deign to grant me, through the intercession of St. Jose Maria, the favor of" + "<break time=\"3s\"/>" + "Amen </speak>",
"prayer to the holy spirit": "<speak>Spirit of wisdom and understanding, enlighten our minds to perceive the mysteries of the universe in relation to eternity. Spirit of right judgment and courage, guide us and make us firm in our baptismal decision to follow Jesus' way of love. Spirit of knowledge and reverence, help us to see the lasting value of justice and mercy in our everyday dealings with one another. May we respect life as we work to solve problems of family and nation, economy and ecology. Spirit of God, spark our faith, hope and love into new action each day. Fill our lives with wonder and awe in your presence which penetrates all creation. Amen.</speak>",
"holy spirit": "<speak>Spirit of wisdom and understanding, enlighten our minds to perceive the mysteries of the universe in relation to eternity. Spirit of right judgment and courage, guide us and make us firm in our baptismal decision to follow Jesus' way of love. Spirit of knowledge and reverence, help us to see the lasting value of justice and mercy in our everyday dealings with one another. May we respect life as we work to solve problems of family and nation, economy and ecology. Spirit of God, spark our faith, hope, and love into new action each day. Fill our lives with wonder and awe in your presence which penetrates all creation. Amen.</speak>",
"saint joseph": "<speak>Oh Saint Joseph, whose protection is so great, so strong, so prompt before the throne of God. I place in you all my interests and desires. Oh St. Joseph, do assist me by your powerful intercession, and obtain for me from your divine Son all spiritual blessings, through Jesus Christ, our Lord. So that, having engaged here below your heavenly power, I may offer my thanksgiving and homage to the most loving of Fathers. Oh, St. Joseph, I never weary of contemplating you, and Jesus asleep in your arms; I dare not approach while He reposes near your heart. Press Him in my name and kiss His fine head for me and ask him to return the Kiss when I draw my dying breath. St. Joseph, Patron of departing souls - Pray for me. Amen.</speak>",
"prayer to saint joseph": "<speak>Oh Saint Joseph, whose protection is so great, so strong, so prompt before the throne of God. I place in you all my interests and desires. Oh St. Joseph, do assist me by your powerful intercession, and obtain for me from your divine Son all spiritual blessings, through Jesus Christ, our Lord. So that, having engaged here below your heavenly power, I may offer my thanksgiving and homage to the most loving of Fathers. Oh, St. Joseph, I never weary of contemplating you, and Jesus asleep in your arms; I dare not approach while He reposes near your heart. Press Him in my name and kiss His fine head for me and ask him to return the Kiss when I draw my dying breath. St. Joseph, Patron of departing souls - Pray for me. Amen.</speak>",
"available payers": "<speak>Our father. Hail mary. Glory Be. The apostle's creed. The nicene creed. Hail holy queen. Anima Christi, Memorare. The Angelus. Saint Michael Prayer. Act of contrition. Miraculous Medal Prayer. Morning offering. Guardian Angel Prayer. Grace before meals. Grace after meals. Serenity prayer. Saint Jose Maria's Prayer. Prayer to the Holy Spirit. Prayer to Saint Joseph.</speak>",
"list prayers": "<speak>Our father. Hail mary. Glory Be. The apostle's creed. The nicene creed. Hail holy queen. Anima Christi, Memorare. The Angelus. Saint Michael Prayer. Act of contrition. Miraculous Medal Prayer. Morning offering. Guardian Angel Prayer. Grace before meals. Grace after meals. Serenity prayer. Saint Jose Maria's Prayer. Prayer to the Holy Spirit. Prayer to Saint Joseph.</speak>",
"available prayers": "<speak>Our father. Hail mary. Glory Be. The apostle's creed. The nicene creed. Hail holy queen. Anima Christi, Memorare. The Angelus. Saint Michael Prayer. Act of contrition. Miraculous Medal Prayer. Morning offering. Guardian Angel Prayer. Grace before meals. Grace after meals. Serenity prayer. Saint Jose Maria's Prayer. Prayer to the Holy Spirit. Prayer to Saint Joseph.</speak>",
"prayer list": "<speak>Our father. Hail mary. Glory Be. The apostle's creed. The nicene creed. Hail holy queen. Anima Christi, Memorare. The Angelus. Saint Michael Prayer. Act of contrition. Miraculous Medal Prayer. Morning offering. Guardian Angel Prayer. Grace before meals. Grace after meals. Serenity prayer. Saint Jose Maria's Prayer. Prayer to the Holy Spirit. Prayer to Saint Joseph.</speak>",
"list all prayers": "<speak>Our father. Hail mary. Glory Be. The apostle's creed. The nicene creed. Hail holy queen. Anima Christi, Memorare. The Angelus. Saint Michael Prayer. Act of contrition. Miraculous Medal Prayer. Morning offering. Guardian Angel Prayer. Grace before meals. Grace after meals. Serenity prayer. Saint Jose Maria's Prayer. Prayer to the Holy Spirit. Prayer to Saint Joseph.</speak>",
"list all prayers that you know": "<speak>Our father. Hail mary. Glory Be. The apostle's creed. The nicene creed. Hail holy queen. Anima Christi, Memorare. The Angelus. Saint Michael Prayer. Act of contrition. Miraculous Medal Prayer. Morning offering. Guardian Angel Prayer. Grace before meals. Grace after meals. Serenity prayer. Saint Jose Maria's Prayer. Prayer to the Holy Spirit. Prayer to Saint Joseph.</speak>",
"all prayers that you know": "<speak>Our father. Hail mary. Glory Be. The apostle's creed. The nicene creed. Hail holy queen. Anima Christi, Memorare. The Angelus. Saint Michael Prayer. Act of contrition. Miraculous Medal Prayer. Morning offering. Guardian Angel Prayer. Grace before meals. Grace after meals. Serenity prayer. Saint Jose Maria's Prayer. Prayer to the Holy Spirit. Prayer to Saint Joseph.</speak>",
"what prayers do you know": "<speak>Our father. Hail mary. Glory Be. The apostle's creed. The nicene creed. Hail holy queen. Anima Christi, Memorare. The Angelus. Saint Michael Prayer. Act of contrition. Miraculous Medal Prayer. Morning offering. Guardian Angel Prayer. Grace before meals. Grace after meals. Serenity prayer. Saint Jose Maria's Prayer. Prayer to the Holy Spirit. Prayer to Saint Joseph.</speak>",
"what prayers do you have": "<speak>Our father. Hail mary. Glory Be. The apostle's creed. The nicene creed. Hail holy queen. Anima Christi, Memorare. The Angelus. Saint Michael Prayer. Act of contrition. Miraculous Medal Prayer. Morning offering. Guardian Angel Prayer. Grace before meals. Grace after meals. Serenity prayer. Saint Jose Maria's Prayer. Prayer to the Holy Spirit. Prayer to Saint Joseph.</speak>",
"what prayers can you read": "<speak>Our father. Hail mary. Glory Be. The apostle's creed. The nicene creed. Hail holy queen. Anima Christi, Memorare. The Angelus. Saint Michael Prayer. Act of contrition. Miraculous Medal Prayer. Morning offering. Guardian Angel Prayer. Grace before meals. Grace after meals. Serenity prayer. Saint Jose Maria's Prayer. Prayer to the Holy Spirit. Prayer to Saint Joseph.</speak>",
"what prayers can you pray": "<speak>Our father. Hail mary. Glory Be. The apostle's creed. The nicene creed. Hail holy queen. Anima Christi, Memorare. The Angelus. Saint Michael Prayer. Act of contrition. Miraculous Medal Prayer. Morning offering. Guardian Angel Prayer. Grace before meals. Grace after meals. Serenity prayer. Saint Jose Maria's Prayer. Prayer to the Holy Spirit. Prayer to Saint Joseph.</speak>",
"which prayers do you know": "<speak>Our father. Hail mary. Glory Be. The apostle's creed. The nicene creed. Hail holy queen. Anima Christi, Memorare. The Angelus. Saint Michael Prayer. Act of contrition. Miraculous Medal Prayer. Morning offering. Guardian Angel Prayer. Grace before meals. Grace after meals. Serenity prayer. Saint Jose Maria's Prayer. Prayer to the Holy Spirit. Prayer to Saint Joseph.</speak>",
"which prayers do you have": "<speak>Our father. Hail mary. Glory Be. The apostle's creed. The nicene creed. Hail holy queen. Anima Christi, Memorare. The Angelus. Saint Michael Prayer. Act of contrition. Miraculous Medal Prayer. Morning offering. Guardian Angel Prayer. Grace before meals. Grace after meals. Serenity prayer. Saint Jose Maria's Prayer. Prayer to the Holy Spirit. Prayer to Saint Joseph.</speak>",
"which prayers can you you read": "<speak>Our father. Hail mary. Glory Be. The apostle's creed. The nicene creed. Hail holy queen. Anima Christi, Memorare. The Angelus. Saint Michael Prayer. Act of contrition. Miraculous Medal Prayer. Morning offering. Guardian Angel Prayer. Grace before meals. Grace after meals. Serenity prayer. Saint Jose Maria's Prayer. Prayer to the Holy Spirit. Prayer to Saint Joseph.</speak>",
"which prayers can you pray": "<speak>Our father. Hail mary. Glory Be. The apostle's creed. The nicene creed. Hail holy queen. Anima Christi, Memorare. The Angelus. Saint Michael Prayer. Act of contrition. Miraculous Medal Prayer. Morning offering. Guardian Angel Prayer. Grace before meals. Grace after meals. Serenity prayer. Saint Jose Maria's Prayer. Prayer to the Holy Spirit. Prayer to Saint Joseph.</speak>"
};
